language: node_js

cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - '12'

git:
  depth: 3

script:
  - yarn test

notifications:
  slack: $SLACK_CHANNEL
  email:
    recipients:
      - $EMAIL_NOTIFICATION
    on_success: always
    on_failure: always

deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key: $API_KEY_HEROKU # desde heroku
  app: travis-platzi
  on:
    repo: jjap005/platzi-store-backend
